### PR TITLE
a demonstration of the minor changes I need to make

### PR DESCRIPTION
**Pull request by NCrusher74**
Here are the changes I want to make. I made them "in place" for now, just to show you what it is I'm intending to do, so then we can work through how to do it in a different file in my own project?

### CODE REVIEW

**Comment by SDGGiesbrecht** [comment]
That is extremely simple. You’re just adding entries to lists. You can do that as‐is. (Otherwise you’d be adding an entry to the list that points to the actual entry elsewhere anyway.) They will be straight‐forward to sort out if there are ever any merge conflicts.

My warning had more to do with when you need to completely rewrite a function or something.

**Comment by NCrusher74** [comment]
Oh yeah, I'm not going to mess with anything that complex, considering I don't actually know C++ and only managed this much because it was so simple and straightforward to change.

I'm toying with the idea of adding to the mp4 atoms as well, because I notice TagLib is missing a lot of the stuff that `MP42Foundation` handled, but it looks like that's a lot more complicated.

The other thing is, however, should I offer THESE changes, minor though they are, to the TagLib project? The license says something about making any changes to TagLib available to the project.

**Comment by SDGGiesbrecht** [comment]
Sure. To do that you will need to check out upstream master, create a new branch, cherry pick this change, and use that branch to create your pull request.

Once it is merged upstream, you are guaranteed to get conflicts on your next update, but you should be able to understand all of them, since you were the cause.

**Comment by NCrusher74** [comment]
Okay I will do that when I get home tonight!

**Pull request closed without merging**
